### PR TITLE
feat: add support for axios response interceptor, remove deprecated methods

### PR DESCRIPTION
**Pull request by yarinvak**
BREAKING CHANGE: removed all deprecated SDK methods

## Pull Request Description

- Adding support for providing an axios response interceptor (https://axios-http.com/docs/interceptors)
- Removing deprecated methods

## Type of change

Please delete options that are not relevant.

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- [X] Locally tested against Fireblocks API

## Checklist:

- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have added corresponding labels to the PR

### CODE REVIEW

**Review by idanya — APPROVED** [review]
Consider refactoring and extracting all the different request methods logic to a single function that uses `this.axiosInstance.request()`

**Review by YoavBZ — CHANGES_REQUESTED** [review]
`return await` is considered redundant, please avoid using it (unless in try-catch block)

**Comment by yarinvak** [comment]
@YoavBZ where do you see it in my changes? I'm not going to fix all old usages in this PR

**Comment by YoavBZ** [comment]
> @YoavBZ where do you see it in my changes? I'm not going to fix all old usages in this PR

Yeah, it's actually the current implementation, we can fix it in the next releases

**Pull request merged**
